org: giovane
service: foodiary-api

provider:
  name: aws
  region: us-east-1
  runtime: nodejs22.x
  memorySize: 128

package:
  individually: true

build:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    exclude:
      - "@aws-sdk/*"
    external:
      - "@aws-sdk/*"

functions:
  hello:
    handler: src/main/functions/hello.handler
    events:
      - httpApi:
          path: /
          method: get
