org: giovane
service: foodiary-api

provider:
  name: aws
  region: us-east-1
  runtime: nodejs22.x
  memorySize: 128

package:
  individually: true

build:
  configFile: ./esbuild.config.mjs

functions:
  hello:
    handler: src/main/functions/hello.handler
    events:
      - httpApi:
          path: /
          method: get
