Resources:
  MealsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:service}-${self:provider.stage}-meals-queue
      VisibilityTimeout: 130 # 130 seconds
      ReceiveMessageWaitTimeSeconds: 20
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt MealsDLQ.Arn
        maxReceiveCount: 2

  MealsDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:service}-${self:provider.stage}-meals-dlq
      MessageRetentionPeriod: 1209600 # 14 days

  MealsDLQAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: ${self:service}-${self:provider.stage}-meals-dlq-alarm
      AlarmDescription: "Alarm is triggered when there are messages in the meals DLQ"
      Namespace: "AWS/SQS"
      MetricName: "ApproximateNumberOfMessagesVisible"
      Dimensions:
        - Name: QueueName
          Value: !GetAtt MealsDLQ.QueueName
      Statistic: Average
      Period: 60
      EvaluationPeriods: 1
      Threshold: 0
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref DLQAlarmsTopic
