Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: ${self:custom.cognito.PoolName}
      DeletionProtection: ACTIVE
      MfaConfiguration: OFF
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
      Schema:
        - Name: internalId
          Required: false
          Mutable: false
          AttributeDataType: String
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
      LambdaConfig:
        PreTokenGenerationConfig:
          LambdaVersion: V3_0
          LambdaArn: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${self:service}-${self:provider.stage}-preTokenGenerationTrigger"
      EmailConfiguration:
        From: ${env:COGNITO_EMAILS_FROM}
        ReplyToEmailAddress: ${env:COGNITO_EMAILS_REPLY_TO}
        EmailSendingAccount: DEVELOPER
        SourceArn: ${env:SES_ARN}

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: ${self:service}-${self:provider.stage}-userpoolclient
      UserPoolId: !Ref UserPool
      GenerateSecret: true
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
      TokenValidityUnits:
        AccessToken: hours
      AccessTokenValidity: 12
      RefreshTokenRotation:
        Feature: ENABLED
        RetryGracePeriodSeconds: 0

  PreTokenGenerationLambdaPermission:
    Type: AWS::Lambda::Permission
    DependsOn: PreTokenGenerationTriggerLambdaFunction
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${self:service}-${self:provider.stage}-preTokenGenerationTrigger"
      Principal: cognito-idp.amazonaws.com
      SourceArn: !GetAtt UserPool.Arn
